//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessmentSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int questionID { get; set; }
        public int attemptID { get; set; }
        public System.Guid UserId { get; set; }
        public string answer1 { get; set; }
        public Nullable<int> mark { get; set; }
        public string comment { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Attempt Attempt { get; set; }
        public virtual Question Question { get; set; }
    }
}
