//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessmentSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attempt()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int attemptID { get; set; }
        public int assessmentID { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<int> attemptScore { get; set; }
        public System.DateTime attemptDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Assessment Assessment { get; set; }
    }
}
